### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BelugaWhale123** [MagusWyvern/ppkomp-2023#1]
For the snail question, you may simplify your code to 
```py
print(int(input()) / 2 - 1)
```
Thank you.

**Comment by MagusWyvern** [comment]
Didn't realize that solution, added your suggestion to the file. Although I still want to keep the old solution as it was how I solved it. Thanks!

Added in [this commit](https://github.com/MagusWyvern/ppkomp-2023/commit/46d047086773eb1e593a5bf9217bc8cfe47f599f)
